image: Ubuntu2204

init:
  - appveyor version
  - ps: Update-AppveyorBuild -Message "Image '$env:APPVEYOR_BUILD_WORKER_IMAGE'@'$env:APPVEYOR_BUILD_WORKER_CLOUD' cloud. $env:APPVEYOR_REPO_COMMIT_MESSAGE"
  - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
  - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
  - sh: |
      [ ! -d "$HOME/Qt/6.9/" ] && echo "No Qt 6.9 dir" || echo "Qt 6.9 dir exists"
  - sh: |
      [ ! -d "$HOME/Qt/6.8/" ] && echo "No Qt 6.8 dir" || echo "Qt 6.8 dir exists"
  - sh: |
      [ ! -d "$HOME/Qt/6.5/" ] && echo "No Qt 6.5 dir" || echo "Qt 6.5 dir exists"

build_script:

  - pushd -- $HOME/Qt
  - find . -mindepth 2 -maxdepth 2 -type d -ls
  - popd
  # Build Qt 5
  - PATH=$HOME/Qt/5.15.2/gcc_64/bin:$HOME/Qt/5.15.2/clang_64/bin:$PATH
  - mkdir build-qt5 && cd build-qt5
  - qmake ../hello.pro
  - make
  - cd ..
  # Build newest Qt
  - PATH=$HOME/Qt/6.9.1/bin:$HOME/Qt/6.9.1:$PATH
  - mkdir build-qt6 && cd build-qt6
  - qmake ../hello.pro
  - make
  - cd ..

  
test_script:
  - sh: |
      [ -f main.o ]
  - sh: |
      [ -x hello ]
  - sh: ./hello
  
#on_finish:
#- sleep 1800
