init:
  - appveyor version
  - ps: Update-AppveyorBuild -Message "Image '$env:APPVEYOR_BUILD_WORKER_IMAGE'@'$env:APPVEYOR_BUILD_WORKER_CLOUD' cloud. $env:APPVEYOR_REPO_COMMIT_MESSAGE"
  - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
  - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD

build_script:
  - cat $HOME/Qt/5.14.2/gcc_64/mkspecs/qconfig.pri
  - PATH=$HOME/Qt/5.14.2/gcc_64/bin:$PATH
  - qmake hello.pro
  - make
  
test_script:
  - sh: |
      [ -f main.o ]
  - sh: |
      [ -x hello ]
  - sh: ./hello
  
