init:
  - appveyor version
  - ps: Update-AppveyorBuild -Message "Image '$env:APPVEYOR_BUILD_WORKER_IMAGE'@'$env:APPVEYOR_BUILD_WORKER_CLOUD' cloud. $env:APPVEYOR_REPO_COMMIT_MESSAGE"
  - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
  - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
  - sh: |
      [ ! -d "$HOME/Qt/6.7/" ] && echo "No Qt 6.7 dir"
  - sh: |
      [ ! -d "$HOME/Qt/6.6/" ] && echo "No Qt 6.6 dir"
  - sh: |
      [ ! -d "$HOME/Qt/6.5/" ] && echo "No Qt 6.5 dir"

build_script:
  - pushd -- $HOME/Qt
  - find . -mindepth 2 -maxdepth 2 -type d -ls
  - popd
  - PATH=$HOME/Qt/5.15.2/gcc_64/bin:$HOME/Qt/5.15.2/clang_64/bin:$PATH
  - qmake hello.pro
  - make
  
test_script:
  - sh: |
      [ -f main.o ]
  - sh: |
      [ -x hello ]
  - sh: ./hello
  
#on_finish:
#- sleep 1800
